runtime: python39

env_variables:
  INSTANCE_CONNECTION_NAME: se4220-project5:us-central1:project5db
  DB_HOST: 104.197.19.83
  DB_USER: root
  DB_PASSWORD: KZ)ghnI*HlKXIm2O
  DB_NAME: project5db
  FLASK_ENV: production
  GOOGLE_CLOUD_PROJECT: SE4220-Project5

entrypoint: gunicorn -b :$PORT app:app

handlers:
  - url: /static
    static_dir: static/

beta_settings:
  cloud_sql_instances: se4220-project5:us-central1:project5db
